name: Deploy Gatsby site to Pages

on:
  push:
    branches: ["main"]  # Deploy on every push to the 'main' branch
  workflow_dispatch:     # Allow manual triggers

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Detect package manager
        id: detect-package-manager
        run: |
          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
            echo "manager=yarn" >> $GITHUB_OUTPUT
          elif [ -f "${{ github.workspace }}/package.json" ]; then
            echo "manager=npm" >> $GITHUB_OUTPUT
          else
            echo "Unable to determine package manager"
            exit 1
          fi
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Adjust if needed
          cache: npm

      - name: Install dependencies
        run: npm install  # You could also use 'yarn install' if using Yarn

      - name: Build Gatsby site
        run: npm run build  # Or 'yarn build'

      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public  # Gatsby outputs the built site in the 'public' folder

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
